/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as TrabajoIndexRouteImport } from './routes/trabajo.index'
import { Route as TrabajoSlugRouteImport } from './routes/trabajo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajoIndexRoute = TrabajoIndexRouteImport.update({
  id: '/trabajo/',
  path: '/trabajo/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajoSlugRoute = TrabajoSlugRouteImport.update({
  id: '/trabajo/$slug',
  path: '/trabajo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/trabajo/$slug': typeof TrabajoSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/trabajo/': typeof TrabajoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/trabajo/$slug': typeof TrabajoSlugRoute
  '/servicios': typeof ServiciosIndexRoute
  '/trabajo': typeof TrabajoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/precios': typeof PreciosRoute
  '/privacidad': typeof PrivacidadRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/trabajo/$slug': typeof TrabajoSlugRoute
  '/servicios/': typeof ServiciosIndexRoute
  '/trabajo/': typeof TrabajoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/precios'
    | '/privacidad'
    | '/servicios/$slug'
    | '/trabajo/$slug'
    | '/servicios/'
    | '/trabajo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/precios'
    | '/privacidad'
    | '/servicios/$slug'
    | '/trabajo/$slug'
    | '/servicios'
    | '/trabajo'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/nosotros'
    | '/precios'
    | '/privacidad'
    | '/servicios/$slug'
    | '/trabajo/$slug'
    | '/servicios/'
    | '/trabajo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  PreciosRoute: typeof PreciosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  TrabajoSlugRoute: typeof TrabajoSlugRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
  TrabajoIndexRoute: typeof TrabajoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajo/': {
      id: '/trabajo/'
      path: '/trabajo'
      fullPath: '/trabajo/'
      preLoaderRoute: typeof TrabajoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabajo/$slug': {
      id: '/trabajo/$slug'
      path: '/trabajo/$slug'
      fullPath: '/trabajo/$slug'
      preLoaderRoute: typeof TrabajoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  PreciosRoute: PreciosRoute,
  PrivacidadRoute: PrivacidadRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  TrabajoSlugRoute: TrabajoSlugRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
  TrabajoIndexRoute: TrabajoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
